name: Deploy with Sitemap

on:
  push:
    branches:
      - main   # only run when pushing to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sitemap dependency
        run: npm install sitemap

      - name: Generate sitemap
        run: node .github/scripts/generate-sitemap.js
        env:
          BASE_URL: "https://millat-fullstack.github.io/all-online-tools"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # your repo root is also your site root
