name: Generate Sitemap

on:
  push:
    branches:
      - main   # or 'master' if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Sitemap Generator
        run: npm install -g @quasibit/gh-pages-sitemap

      - name: Generate sitemap
        run: |
          npx @quasibit/gh-pages-sitemap \
            --base-url https://millat-fullstack.github.io/all-online-tools \
            --output ./sitemap.xml

      - name: Commit sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push
