name: Auto-generate sitemap

on:
  push:
    branches:
      - main  # change if your branch is 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important for using GITHUB_TOKEN

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          # Find all HTML files and skip hidden folders
          find . -name "*.html" ! -path "*/.*" | sed 's|^\./||' | while read file; do
            echo "  <url><loc>https://millat-fullstack.github.io/all-online-tools/${file}</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
