name: Auto-generate sitemap

on:
  push:
    branches:
      - main   # triggers when you push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -name "*.html" ! -path "*/.*" ! -name "sitemap.xml" | sed 's|^\./||' | while read file; do
            echo "  <url><loc>https://millat-fullstack.github.io/all-online-tools/${file}</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Push sitemap to gh-pages-sitemap branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages-sitemap
          git add sitemap.xml
          git commit -m "Auto-generate sitemap" || echo "No changes to commit"
          git push -u origin gh-pages-sitemap --force
