name: Build and Deploy with Sitemap

on:
  push:
    branches:
      - main   # or change to your deploy branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sitemap dependencies
        run: npm install sitemap

      - name: Generate sitemap
        run: node .github/scripts/generate-sitemap.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # change if your build outputs to /dist or /build
